name: E2E Tests

on:
  pull_request:
    paths:
      - "projects/project-generator/**"
  push:
    branches:
      - main
    paths:
      - "projects/project-generator/**"

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.13.1

      - name: Install dependencies
        run: pnpm install

      - name: Build project generator
        run: pnpm --filter create-vite-apollo-fs build

      - name: Generate test project
        run: |
          chmod +x ./projects/project-generator/dist/generator.js
          ./projects/project-generator/dist/generator.js --destinationPath=myProject --apiName=my-api --webUiName=my-web-ui

      - name: Install dependencies in generated project
        run: |
          cd myProject
          pnpm install

      - name: Start development server in background
        run: |
          cd myProject
          pnpm dev &
          echo $! > dev_server.pid

      - name: Wait for server to be ready
        run: |
          timeout 60 bash -c 'until curl -f http://localhost:5173; do sleep 2; done'

      - name: Install Playwright browsers and dependencies
        run: |
          cd projects/project-generator-e2e
          npx playwright install --with-deps

      - name: Run E2E tests
        run: |
          cd projects/project-generator-e2e
          npm run test

      - name: Stop development server
        if: always()
        run: |
          if [ -f myProject/dev_server.pid ]; then
            kill $(cat myProject/dev_server.pid) || true
          fi

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: projects/project-generator-e2e/playwright-report/
